// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/byxorna/nycmesh-tool/models"
)

// PostDevicesIDSystemUnmsHostnameReachableReader is a Reader for the PostDevicesIDSystemUnmsHostnameReachable structure.
type PostDevicesIDSystemUnmsHostnameReachableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDevicesIDSystemUnmsHostnameReachableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDevicesIDSystemUnmsHostnameReachableOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostDevicesIDSystemUnmsHostnameReachableBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostDevicesIDSystemUnmsHostnameReachableUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostDevicesIDSystemUnmsHostnameReachableForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostDevicesIDSystemUnmsHostnameReachableNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDevicesIDSystemUnmsHostnameReachableInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostDevicesIDSystemUnmsHostnameReachableOK creates a PostDevicesIDSystemUnmsHostnameReachableOK with default headers values
func NewPostDevicesIDSystemUnmsHostnameReachableOK() *PostDevicesIDSystemUnmsHostnameReachableOK {
	return &PostDevicesIDSystemUnmsHostnameReachableOK{}
}

/* PostDevicesIDSystemUnmsHostnameReachableOK describes a response with status code 200, with default header values.

Successful
*/
type PostDevicesIDSystemUnmsHostnameReachableOK struct {
	Payload bool
}

func (o *PostDevicesIDSystemUnmsHostnameReachableOK) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/system/unms/hostname/reachable][%d] postDevicesIdSystemUnmsHostnameReachableOK  %+v", 200, o.Payload)
}
func (o *PostDevicesIDSystemUnmsHostnameReachableOK) GetPayload() bool {
	return o.Payload
}

func (o *PostDevicesIDSystemUnmsHostnameReachableOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesIDSystemUnmsHostnameReachableBadRequest creates a PostDevicesIDSystemUnmsHostnameReachableBadRequest with default headers values
func NewPostDevicesIDSystemUnmsHostnameReachableBadRequest() *PostDevicesIDSystemUnmsHostnameReachableBadRequest {
	return &PostDevicesIDSystemUnmsHostnameReachableBadRequest{}
}

/* PostDevicesIDSystemUnmsHostnameReachableBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostDevicesIDSystemUnmsHostnameReachableBadRequest struct {
	Payload *models.Error
}

func (o *PostDevicesIDSystemUnmsHostnameReachableBadRequest) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/system/unms/hostname/reachable][%d] postDevicesIdSystemUnmsHostnameReachableBadRequest  %+v", 400, o.Payload)
}
func (o *PostDevicesIDSystemUnmsHostnameReachableBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesIDSystemUnmsHostnameReachableBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesIDSystemUnmsHostnameReachableUnauthorized creates a PostDevicesIDSystemUnmsHostnameReachableUnauthorized with default headers values
func NewPostDevicesIDSystemUnmsHostnameReachableUnauthorized() *PostDevicesIDSystemUnmsHostnameReachableUnauthorized {
	return &PostDevicesIDSystemUnmsHostnameReachableUnauthorized{}
}

/* PostDevicesIDSystemUnmsHostnameReachableUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostDevicesIDSystemUnmsHostnameReachableUnauthorized struct {
	Payload *models.Error
}

func (o *PostDevicesIDSystemUnmsHostnameReachableUnauthorized) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/system/unms/hostname/reachable][%d] postDevicesIdSystemUnmsHostnameReachableUnauthorized  %+v", 401, o.Payload)
}
func (o *PostDevicesIDSystemUnmsHostnameReachableUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesIDSystemUnmsHostnameReachableUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesIDSystemUnmsHostnameReachableForbidden creates a PostDevicesIDSystemUnmsHostnameReachableForbidden with default headers values
func NewPostDevicesIDSystemUnmsHostnameReachableForbidden() *PostDevicesIDSystemUnmsHostnameReachableForbidden {
	return &PostDevicesIDSystemUnmsHostnameReachableForbidden{}
}

/* PostDevicesIDSystemUnmsHostnameReachableForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostDevicesIDSystemUnmsHostnameReachableForbidden struct {
	Payload *models.Error
}

func (o *PostDevicesIDSystemUnmsHostnameReachableForbidden) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/system/unms/hostname/reachable][%d] postDevicesIdSystemUnmsHostnameReachableForbidden  %+v", 403, o.Payload)
}
func (o *PostDevicesIDSystemUnmsHostnameReachableForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesIDSystemUnmsHostnameReachableForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesIDSystemUnmsHostnameReachableNotFound creates a PostDevicesIDSystemUnmsHostnameReachableNotFound with default headers values
func NewPostDevicesIDSystemUnmsHostnameReachableNotFound() *PostDevicesIDSystemUnmsHostnameReachableNotFound {
	return &PostDevicesIDSystemUnmsHostnameReachableNotFound{}
}

/* PostDevicesIDSystemUnmsHostnameReachableNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostDevicesIDSystemUnmsHostnameReachableNotFound struct {
	Payload *models.Error
}

func (o *PostDevicesIDSystemUnmsHostnameReachableNotFound) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/system/unms/hostname/reachable][%d] postDevicesIdSystemUnmsHostnameReachableNotFound  %+v", 404, o.Payload)
}
func (o *PostDevicesIDSystemUnmsHostnameReachableNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesIDSystemUnmsHostnameReachableNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesIDSystemUnmsHostnameReachableInternalServerError creates a PostDevicesIDSystemUnmsHostnameReachableInternalServerError with default headers values
func NewPostDevicesIDSystemUnmsHostnameReachableInternalServerError() *PostDevicesIDSystemUnmsHostnameReachableInternalServerError {
	return &PostDevicesIDSystemUnmsHostnameReachableInternalServerError{}
}

/* PostDevicesIDSystemUnmsHostnameReachableInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostDevicesIDSystemUnmsHostnameReachableInternalServerError struct {
	Payload *models.Error
}

func (o *PostDevicesIDSystemUnmsHostnameReachableInternalServerError) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/system/unms/hostname/reachable][%d] postDevicesIdSystemUnmsHostnameReachableInternalServerError  %+v", 500, o.Payload)
}
func (o *PostDevicesIDSystemUnmsHostnameReachableInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesIDSystemUnmsHostnameReachableInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
