// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/byxorna/nycmesh-tool/models"
)

// PostDevicesIDRouterRoutesBlockReader is a Reader for the PostDevicesIDRouterRoutesBlock structure.
type PostDevicesIDRouterRoutesBlockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDevicesIDRouterRoutesBlockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDevicesIDRouterRoutesBlockOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostDevicesIDRouterRoutesBlockBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostDevicesIDRouterRoutesBlockUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostDevicesIDRouterRoutesBlockForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostDevicesIDRouterRoutesBlockNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDevicesIDRouterRoutesBlockInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostDevicesIDRouterRoutesBlockOK creates a PostDevicesIDRouterRoutesBlockOK with default headers values
func NewPostDevicesIDRouterRoutesBlockOK() *PostDevicesIDRouterRoutesBlockOK {
	return &PostDevicesIDRouterRoutesBlockOK{}
}

/* PostDevicesIDRouterRoutesBlockOK describes a response with status code 200, with default header values.

Successful
*/
type PostDevicesIDRouterRoutesBlockOK struct {
	Payload *models.Status
}

func (o *PostDevicesIDRouterRoutesBlockOK) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/router/routes/block][%d] postDevicesIdRouterRoutesBlockOK  %+v", 200, o.Payload)
}
func (o *PostDevicesIDRouterRoutesBlockOK) GetPayload() *models.Status {
	return o.Payload
}

func (o *PostDevicesIDRouterRoutesBlockOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesIDRouterRoutesBlockBadRequest creates a PostDevicesIDRouterRoutesBlockBadRequest with default headers values
func NewPostDevicesIDRouterRoutesBlockBadRequest() *PostDevicesIDRouterRoutesBlockBadRequest {
	return &PostDevicesIDRouterRoutesBlockBadRequest{}
}

/* PostDevicesIDRouterRoutesBlockBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostDevicesIDRouterRoutesBlockBadRequest struct {
	Payload *models.Error
}

func (o *PostDevicesIDRouterRoutesBlockBadRequest) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/router/routes/block][%d] postDevicesIdRouterRoutesBlockBadRequest  %+v", 400, o.Payload)
}
func (o *PostDevicesIDRouterRoutesBlockBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesIDRouterRoutesBlockBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesIDRouterRoutesBlockUnauthorized creates a PostDevicesIDRouterRoutesBlockUnauthorized with default headers values
func NewPostDevicesIDRouterRoutesBlockUnauthorized() *PostDevicesIDRouterRoutesBlockUnauthorized {
	return &PostDevicesIDRouterRoutesBlockUnauthorized{}
}

/* PostDevicesIDRouterRoutesBlockUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostDevicesIDRouterRoutesBlockUnauthorized struct {
	Payload *models.Error
}

func (o *PostDevicesIDRouterRoutesBlockUnauthorized) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/router/routes/block][%d] postDevicesIdRouterRoutesBlockUnauthorized  %+v", 401, o.Payload)
}
func (o *PostDevicesIDRouterRoutesBlockUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesIDRouterRoutesBlockUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesIDRouterRoutesBlockForbidden creates a PostDevicesIDRouterRoutesBlockForbidden with default headers values
func NewPostDevicesIDRouterRoutesBlockForbidden() *PostDevicesIDRouterRoutesBlockForbidden {
	return &PostDevicesIDRouterRoutesBlockForbidden{}
}

/* PostDevicesIDRouterRoutesBlockForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostDevicesIDRouterRoutesBlockForbidden struct {
	Payload *models.Error
}

func (o *PostDevicesIDRouterRoutesBlockForbidden) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/router/routes/block][%d] postDevicesIdRouterRoutesBlockForbidden  %+v", 403, o.Payload)
}
func (o *PostDevicesIDRouterRoutesBlockForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesIDRouterRoutesBlockForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesIDRouterRoutesBlockNotFound creates a PostDevicesIDRouterRoutesBlockNotFound with default headers values
func NewPostDevicesIDRouterRoutesBlockNotFound() *PostDevicesIDRouterRoutesBlockNotFound {
	return &PostDevicesIDRouterRoutesBlockNotFound{}
}

/* PostDevicesIDRouterRoutesBlockNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostDevicesIDRouterRoutesBlockNotFound struct {
	Payload *models.Error
}

func (o *PostDevicesIDRouterRoutesBlockNotFound) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/router/routes/block][%d] postDevicesIdRouterRoutesBlockNotFound  %+v", 404, o.Payload)
}
func (o *PostDevicesIDRouterRoutesBlockNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesIDRouterRoutesBlockNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDevicesIDRouterRoutesBlockInternalServerError creates a PostDevicesIDRouterRoutesBlockInternalServerError with default headers values
func NewPostDevicesIDRouterRoutesBlockInternalServerError() *PostDevicesIDRouterRoutesBlockInternalServerError {
	return &PostDevicesIDRouterRoutesBlockInternalServerError{}
}

/* PostDevicesIDRouterRoutesBlockInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostDevicesIDRouterRoutesBlockInternalServerError struct {
	Payload *models.Error
}

func (o *PostDevicesIDRouterRoutesBlockInternalServerError) Error() string {
	return fmt.Sprintf("[POST /devices/{id}/router/routes/block][%d] postDevicesIdRouterRoutesBlockInternalServerError  %+v", 500, o.Payload)
}
func (o *PostDevicesIDRouterRoutesBlockInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDevicesIDRouterRoutesBlockInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
