// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDevicesDeviceidInterfacesInterfacenameResetParams creates a new PostDevicesDeviceidInterfacesInterfacenameResetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDevicesDeviceidInterfacesInterfacenameResetParams() *PostDevicesDeviceidInterfacesInterfacenameResetParams {
	return &PostDevicesDeviceidInterfacesInterfacenameResetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDevicesDeviceidInterfacesInterfacenameResetParamsWithTimeout creates a new PostDevicesDeviceidInterfacesInterfacenameResetParams object
// with the ability to set a timeout on a request.
func NewPostDevicesDeviceidInterfacesInterfacenameResetParamsWithTimeout(timeout time.Duration) *PostDevicesDeviceidInterfacesInterfacenameResetParams {
	return &PostDevicesDeviceidInterfacesInterfacenameResetParams{
		timeout: timeout,
	}
}

// NewPostDevicesDeviceidInterfacesInterfacenameResetParamsWithContext creates a new PostDevicesDeviceidInterfacesInterfacenameResetParams object
// with the ability to set a context for a request.
func NewPostDevicesDeviceidInterfacesInterfacenameResetParamsWithContext(ctx context.Context) *PostDevicesDeviceidInterfacesInterfacenameResetParams {
	return &PostDevicesDeviceidInterfacesInterfacenameResetParams{
		Context: ctx,
	}
}

// NewPostDevicesDeviceidInterfacesInterfacenameResetParamsWithHTTPClient creates a new PostDevicesDeviceidInterfacesInterfacenameResetParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDevicesDeviceidInterfacesInterfacenameResetParamsWithHTTPClient(client *http.Client) *PostDevicesDeviceidInterfacesInterfacenameResetParams {
	return &PostDevicesDeviceidInterfacesInterfacenameResetParams{
		HTTPClient: client,
	}
}

/* PostDevicesDeviceidInterfacesInterfacenameResetParams contains all the parameters to send to the API endpoint
   for the post devices deviceid interfaces interfacename reset operation.

   Typically these are written to a http.Request.
*/
type PostDevicesDeviceidInterfacesInterfacenameResetParams struct {

	// DeviceID.
	DeviceID string

	// InterfaceName.
	InterfaceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post devices deviceid interfaces interfacename reset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) WithDefaults() *PostDevicesDeviceidInterfacesInterfacenameResetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post devices deviceid interfaces interfacename reset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post devices deviceid interfaces interfacename reset params
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) WithTimeout(timeout time.Duration) *PostDevicesDeviceidInterfacesInterfacenameResetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post devices deviceid interfaces interfacename reset params
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post devices deviceid interfaces interfacename reset params
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) WithContext(ctx context.Context) *PostDevicesDeviceidInterfacesInterfacenameResetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post devices deviceid interfaces interfacename reset params
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post devices deviceid interfaces interfacename reset params
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) WithHTTPClient(client *http.Client) *PostDevicesDeviceidInterfacesInterfacenameResetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post devices deviceid interfaces interfacename reset params
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the post devices deviceid interfaces interfacename reset params
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) WithDeviceID(deviceID string) *PostDevicesDeviceidInterfacesInterfacenameResetParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the post devices deviceid interfaces interfacename reset params
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithInterfaceName adds the interfaceName to the post devices deviceid interfaces interfacename reset params
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) WithInterfaceName(interfaceName string) *PostDevicesDeviceidInterfacesInterfacenameResetParams {
	o.SetInterfaceName(interfaceName)
	return o
}

// SetInterfaceName adds the interfaceName to the post devices deviceid interfaces interfacename reset params
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) SetInterfaceName(interfaceName string) {
	o.InterfaceName = interfaceName
}

// WriteToRequest writes these params to a swagger request
func (o *PostDevicesDeviceidInterfacesInterfacenameResetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	// path param interfaceName
	if err := r.SetPathParam("interfaceName", o.InterfaceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
