// Code generated by go-swagger; DO NOT EDIT.

package installations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/byxorna/nycmesh-tool/models"
)

// NewPostInstallationsParams creates a new PostInstallationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostInstallationsParams() *PostInstallationsParams {
	return &PostInstallationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostInstallationsParamsWithTimeout creates a new PostInstallationsParams object
// with the ability to set a timeout on a request.
func NewPostInstallationsParamsWithTimeout(timeout time.Duration) *PostInstallationsParams {
	return &PostInstallationsParams{
		timeout: timeout,
	}
}

// NewPostInstallationsParamsWithContext creates a new PostInstallationsParams object
// with the ability to set a context for a request.
func NewPostInstallationsParamsWithContext(ctx context.Context) *PostInstallationsParams {
	return &PostInstallationsParams{
		Context: ctx,
	}
}

// NewPostInstallationsParamsWithHTTPClient creates a new PostInstallationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostInstallationsParamsWithHTTPClient(client *http.Client) *PostInstallationsParams {
	return &PostInstallationsParams{
		HTTPClient: client,
	}
}

/* PostInstallationsParams contains all the parameters to send to the API endpoint
   for the post installations operation.

   Typically these are written to a http.Request.
*/
type PostInstallationsParams struct {

	// Body.
	Body *models.InstallationPayload

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post installations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInstallationsParams) WithDefaults() *PostInstallationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post installations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInstallationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post installations params
func (o *PostInstallationsParams) WithTimeout(timeout time.Duration) *PostInstallationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post installations params
func (o *PostInstallationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post installations params
func (o *PostInstallationsParams) WithContext(ctx context.Context) *PostInstallationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post installations params
func (o *PostInstallationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post installations params
func (o *PostInstallationsParams) WithHTTPClient(client *http.Client) *PostInstallationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post installations params
func (o *PostInstallationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post installations params
func (o *PostInstallationsParams) WithBody(body *models.InstallationPayload) *PostInstallationsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post installations params
func (o *PostInstallationsParams) SetBody(body *models.InstallationPayload) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostInstallationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
