// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/byxorna/nycmesh-tool/models"
	"github.com/spf13/cobra"
)

// Schema cli for Airmax

// register flags to command
func registerModelAirmaxFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerAirmaxMode(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerAirmaxWds(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerAirmaxMode(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	modeDescription := `Required. `

	var modeFlagName string
	if cmdPrefix == "" {
		modeFlagName = "mode"
	} else {
		modeFlagName = fmt.Sprintf("%v.mode", cmdPrefix)
	}

	var modeFlagDefault string

	_ = cmd.PersistentFlags().String(modeFlagName, modeFlagDefault, modeDescription)

	return nil
}

func registerAirmaxWds(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	wdsDescription := `Required. `

	var wdsFlagName string
	if cmdPrefix == "" {
		wdsFlagName = "wds"
	} else {
		wdsFlagName = fmt.Sprintf("%v.wds", cmdPrefix)
	}

	var wdsFlagDefault bool

	_ = cmd.PersistentFlags().Bool(wdsFlagName, wdsFlagDefault, wdsDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelAirmaxFlags(depth int, m *models.Airmax, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, modeAdded := retrieveAirmaxModeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || modeAdded

	err, wdsAdded := retrieveAirmaxWdsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || wdsAdded

	return nil, retAdded
}

func retrieveAirmaxModeFlags(depth int, m *models.Airmax, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	modeFlagName := fmt.Sprintf("%v.mode", cmdPrefix)
	if cmd.Flags().Changed(modeFlagName) {

		var modeFlagName string
		if cmdPrefix == "" {
			modeFlagName = "mode"
		} else {
			modeFlagName = fmt.Sprintf("%v.mode", cmdPrefix)
		}

		modeFlagValue, err := cmd.Flags().GetString(modeFlagName)
		if err != nil {
			return err, false
		}
		m.Mode = &modeFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveAirmaxWdsFlags(depth int, m *models.Airmax, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	wdsFlagName := fmt.Sprintf("%v.wds", cmdPrefix)
	if cmd.Flags().Changed(wdsFlagName) {

		var wdsFlagName string
		if cmdPrefix == "" {
			wdsFlagName = "wds"
		} else {
			wdsFlagName = fmt.Sprintf("%v.wds", cmdPrefix)
		}

		wdsFlagValue, err := cmd.Flags().GetBool(wdsFlagName)
		if err != nil {
			return err, false
		}
		m.Wds = &wdsFlagValue

		retAdded = true
	}

	return nil, retAdded
}
