// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/byxorna/nycmesh-tool/models"
	"github.com/go-openapi/swag"

	"github.com/spf13/cobra"
)

// Schema cli for DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1

// register flags to command
func registerModelDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Flags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Antenna(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ApDevice(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ApMac(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Authentication(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1AvailableTxPowerRange(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CableLength(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CableSnr(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Ccq(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ChannelWidth(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CountryCode(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Frequency(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1FrequencyBands(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1FrequencyCenter(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1GpsSignal(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Location(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1NoiseFloor(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Polling(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ReceiveChains(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RemoteSignal(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RemoteSignal60g(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RxCinr(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Security(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Series(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SignalChain(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SignalRemoteChain(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Ssid(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1StationName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1StationsCount(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TddFraming(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TransmitChains(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TransmitPower(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Wds(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WirelessMode(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WlanRxBytes(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WlanTxBytes(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Antenna(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	antennaDescription := ``

	var antennaFlagName string
	if cmdPrefix == "" {
		antennaFlagName = "antenna"
	} else {
		antennaFlagName = fmt.Sprintf("%v.antenna", cmdPrefix)
	}

	var antennaFlagDefault string

	_ = cmd.PersistentFlags().String(antennaFlagName, antennaFlagDefault, antennaDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ApDevice(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var apDeviceFlagName string
	if cmdPrefix == "" {
		apDeviceFlagName = "apDevice"
	} else {
		apDeviceFlagName = fmt.Sprintf("%v.apDevice", cmdPrefix)
	}

	if err := registerModelApDeviceFlags(depth+1, apDeviceFlagName, cmd); err != nil {
		return err
	}

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ApMac(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	apMacDescription := ``

	var apMacFlagName string
	if cmdPrefix == "" {
		apMacFlagName = "apMac"
	} else {
		apMacFlagName = fmt.Sprintf("%v.apMac", cmdPrefix)
	}

	var apMacFlagDefault string

	_ = cmd.PersistentFlags().String(apMacFlagName, apMacFlagDefault, apMacDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Authentication(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	authenticationDescription := `Enum: ["psk","psk2","ent","none"]. Required. `

	var authenticationFlagName string
	if cmdPrefix == "" {
		authenticationFlagName = "authentication"
	} else {
		authenticationFlagName = fmt.Sprintf("%v.authentication", cmdPrefix)
	}

	var authenticationFlagDefault string

	_ = cmd.PersistentFlags().String(authenticationFlagName, authenticationFlagDefault, authenticationDescription)

	if err := cmd.RegisterFlagCompletionFunc(authenticationFlagName,
		func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
			var res []string
			if err := json.Unmarshal([]byte(`["psk","psk2","ent","none"]`), &res); err != nil {
				panic(err)
			}
			return res, cobra.ShellCompDirectiveDefault
		}); err != nil {
		return err
	}

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1AvailableTxPowerRange(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var availableTxPowerRangeFlagName string
	if cmdPrefix == "" {
		availableTxPowerRangeFlagName = "availableTxPowerRange"
	} else {
		availableTxPowerRangeFlagName = fmt.Sprintf("%v.availableTxPowerRange", cmdPrefix)
	}

	if err := registerModelAvailableTxPowerRangeFlags(depth+1, availableTxPowerRangeFlagName, cmd); err != nil {
		return err
	}

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CableLength(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	cableLengthDescription := `Cable Length from eth0 interface in meters. When below values is null cable is long less then 20m.`

	var cableLengthFlagName string
	if cmdPrefix == "" {
		cableLengthFlagName = "cableLength"
	} else {
		cableLengthFlagName = fmt.Sprintf("%v.cableLength", cmdPrefix)
	}

	var cableLengthFlagDefault float64

	_ = cmd.PersistentFlags().Float64(cableLengthFlagName, cableLengthFlagDefault, cableLengthDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CableSnr(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	cableSnrDescription := `Average signal-to-noise ratio on eth0 interface in dB`

	var cableSnrFlagName string
	if cmdPrefix == "" {
		cableSnrFlagName = "cableSnr"
	} else {
		cableSnrFlagName = fmt.Sprintf("%v.cableSnr", cmdPrefix)
	}

	var cableSnrFlagDefault float64

	_ = cmd.PersistentFlags().Float64(cableSnrFlagName, cableSnrFlagDefault, cableSnrDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Ccq(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	ccqDescription := ``

	var ccqFlagName string
	if cmdPrefix == "" {
		ccqFlagName = "ccq"
	} else {
		ccqFlagName = fmt.Sprintf("%v.ccq", cmdPrefix)
	}

	var ccqFlagDefault float64

	_ = cmd.PersistentFlags().Float64(ccqFlagName, ccqFlagDefault, ccqDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ChannelWidth(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	channelWidthDescription := `Required. `

	var channelWidthFlagName string
	if cmdPrefix == "" {
		channelWidthFlagName = "channelWidth"
	} else {
		channelWidthFlagName = fmt.Sprintf("%v.channelWidth", cmdPrefix)
	}

	var channelWidthFlagDefault int64

	_ = cmd.PersistentFlags().Int64(channelWidthFlagName, channelWidthFlagDefault, channelWidthDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CountryCode(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	countryCodeDescription := `Required. `

	var countryCodeFlagName string
	if cmdPrefix == "" {
		countryCodeFlagName = "countryCode"
	} else {
		countryCodeFlagName = fmt.Sprintf("%v.countryCode", cmdPrefix)
	}

	var countryCodeFlagDefault int64

	_ = cmd.PersistentFlags().Int64(countryCodeFlagName, countryCodeFlagDefault, countryCodeDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Frequency(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	frequencyDescription := ``

	var frequencyFlagName string
	if cmdPrefix == "" {
		frequencyFlagName = "frequency"
	} else {
		frequencyFlagName = fmt.Sprintf("%v.frequency", cmdPrefix)
	}

	var frequencyFlagDefault float64

	_ = cmd.PersistentFlags().Float64(frequencyFlagName, frequencyFlagDefault, frequencyDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1FrequencyBands(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: frequencyBands FrequencyBands3 array type is not supported by go-swagger cli yet

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1FrequencyCenter(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	frequencyCenterDescription := ``

	var frequencyCenterFlagName string
	if cmdPrefix == "" {
		frequencyCenterFlagName = "frequencyCenter"
	} else {
		frequencyCenterFlagName = fmt.Sprintf("%v.frequencyCenter", cmdPrefix)
	}

	var frequencyCenterFlagDefault string

	_ = cmd.PersistentFlags().String(frequencyCenterFlagName, frequencyCenterFlagDefault, frequencyCenterDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1GpsSignal(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	gpsSignalDescription := ``

	var gpsSignalFlagName string
	if cmdPrefix == "" {
		gpsSignalFlagName = "gpsSignal"
	} else {
		gpsSignalFlagName = fmt.Sprintf("%v.gpsSignal", cmdPrefix)
	}

	var gpsSignalFlagDefault float64

	_ = cmd.PersistentFlags().Float64(gpsSignalFlagName, gpsSignalFlagDefault, gpsSignalDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Location(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var locationFlagName string
	if cmdPrefix == "" {
		locationFlagName = "location"
	} else {
		locationFlagName = fmt.Sprintf("%v.location", cmdPrefix)
	}

	if err := registerModelLocationFlags(depth+1, locationFlagName, cmd); err != nil {
		return err
	}

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1NoiseFloor(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	noiseFloorDescription := ``

	var noiseFloorFlagName string
	if cmdPrefix == "" {
		noiseFloorFlagName = "noiseFloor"
	} else {
		noiseFloorFlagName = fmt.Sprintf("%v.noiseFloor", cmdPrefix)
	}

	var noiseFloorFlagDefault string

	_ = cmd.PersistentFlags().String(noiseFloorFlagName, noiseFloorFlagDefault, noiseFloorDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Polling(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var pollingFlagName string
	if cmdPrefix == "" {
		pollingFlagName = "polling"
	} else {
		pollingFlagName = fmt.Sprintf("%v.polling", cmdPrefix)
	}

	if err := registerModelPollingFlags(depth+1, pollingFlagName, cmd); err != nil {
		return err
	}

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ReceiveChains(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	receiveChainsDescription := ``

	var receiveChainsFlagName string
	if cmdPrefix == "" {
		receiveChainsFlagName = "receiveChains"
	} else {
		receiveChainsFlagName = fmt.Sprintf("%v.receiveChains", cmdPrefix)
	}

	var receiveChainsFlagDefault float64

	_ = cmd.PersistentFlags().Float64(receiveChainsFlagName, receiveChainsFlagDefault, receiveChainsDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RemoteSignal(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	remoteSignalDescription := ``

	var remoteSignalFlagName string
	if cmdPrefix == "" {
		remoteSignalFlagName = "remoteSignal"
	} else {
		remoteSignalFlagName = fmt.Sprintf("%v.remoteSignal", cmdPrefix)
	}

	var remoteSignalFlagDefault float64

	_ = cmd.PersistentFlags().Float64(remoteSignalFlagName, remoteSignalFlagDefault, remoteSignalDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RemoteSignal60g(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	remoteSignal60gDescription := ``

	var remoteSignal60gFlagName string
	if cmdPrefix == "" {
		remoteSignal60gFlagName = "remoteSignal60g"
	} else {
		remoteSignal60gFlagName = fmt.Sprintf("%v.remoteSignal60g", cmdPrefix)
	}

	var remoteSignal60gFlagDefault float64

	_ = cmd.PersistentFlags().Float64(remoteSignal60gFlagName, remoteSignal60gFlagDefault, remoteSignal60gDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RxCinr(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	rxCinrDescription := `Carrier to Interference-plus-Noise Ratio in dB on wireless`

	var rxCinrFlagName string
	if cmdPrefix == "" {
		rxCinrFlagName = "rxCinr"
	} else {
		rxCinrFlagName = fmt.Sprintf("%v.rxCinr", cmdPrefix)
	}

	var rxCinrFlagDefault float64

	_ = cmd.PersistentFlags().Float64(rxCinrFlagName, rxCinrFlagDefault, rxCinrDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Security(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	securityDescription := `Enum: ["wep","wpa","wpa-psk","wpa2","enabled","none"]. Required. `

	var securityFlagName string
	if cmdPrefix == "" {
		securityFlagName = "security"
	} else {
		securityFlagName = fmt.Sprintf("%v.security", cmdPrefix)
	}

	var securityFlagDefault string

	_ = cmd.PersistentFlags().String(securityFlagName, securityFlagDefault, securityDescription)

	if err := cmd.RegisterFlagCompletionFunc(securityFlagName,
		func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
			var res []string
			if err := json.Unmarshal([]byte(`["wep","wpa","wpa-psk","wpa2","enabled","none"]`), &res); err != nil {
				panic(err)
			}
			return res, cobra.ShellCompDirectiveDefault
		}); err != nil {
		return err
	}

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Series(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	seriesDescription := `Enum: ["AC","M","G60"]. Required. `

	var seriesFlagName string
	if cmdPrefix == "" {
		seriesFlagName = "series"
	} else {
		seriesFlagName = fmt.Sprintf("%v.series", cmdPrefix)
	}

	var seriesFlagDefault string

	_ = cmd.PersistentFlags().String(seriesFlagName, seriesFlagDefault, seriesDescription)

	if err := cmd.RegisterFlagCompletionFunc(seriesFlagName,
		func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
			var res []string
			if err := json.Unmarshal([]byte(`["AC","M","G60"]`), &res); err != nil {
				panic(err)
			}
			return res, cobra.ShellCompDirectiveDefault
		}); err != nil {
		return err
	}

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SignalChain(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: signalChain SignalChain array type is not supported by go-swagger cli yet

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SignalRemoteChain(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: signalRemoteChain SignalRemoteChain array type is not supported by go-swagger cli yet

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Ssid(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	ssidDescription := `SSID`

	var ssidFlagName string
	if cmdPrefix == "" {
		ssidFlagName = "ssid"
	} else {
		ssidFlagName = fmt.Sprintf("%v.ssid", cmdPrefix)
	}

	var ssidFlagDefault string

	_ = cmd.PersistentFlags().String(ssidFlagName, ssidFlagDefault, ssidDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1StationName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	stationNameDescription := ``

	var stationNameFlagName string
	if cmdPrefix == "" {
		stationNameFlagName = "stationName"
	} else {
		stationNameFlagName = fmt.Sprintf("%v.stationName", cmdPrefix)
	}

	var stationNameFlagDefault string

	_ = cmd.PersistentFlags().String(stationNameFlagName, stationNameFlagDefault, stationNameDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1StationsCount(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	stationsCountDescription := ``

	var stationsCountFlagName string
	if cmdPrefix == "" {
		stationsCountFlagName = "stationsCount"
	} else {
		stationsCountFlagName = fmt.Sprintf("%v.stationsCount", cmdPrefix)
	}

	var stationsCountFlagDefault float64

	_ = cmd.PersistentFlags().Float64(stationsCountFlagName, stationsCountFlagDefault, stationsCountDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TddFraming(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	tddFramingDescription := ``

	var tddFramingFlagName string
	if cmdPrefix == "" {
		tddFramingFlagName = "tddFraming"
	} else {
		tddFramingFlagName = fmt.Sprintf("%v.tddFraming", cmdPrefix)
	}

	var tddFramingFlagDefault string

	_ = cmd.PersistentFlags().String(tddFramingFlagName, tddFramingFlagDefault, tddFramingDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TransmitChains(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	transmitChainsDescription := ``

	var transmitChainsFlagName string
	if cmdPrefix == "" {
		transmitChainsFlagName = "transmitChains"
	} else {
		transmitChainsFlagName = fmt.Sprintf("%v.transmitChains", cmdPrefix)
	}

	var transmitChainsFlagDefault float64

	_ = cmd.PersistentFlags().Float64(transmitChainsFlagName, transmitChainsFlagDefault, transmitChainsDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TransmitPower(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	transmitPowerDescription := ``

	var transmitPowerFlagName string
	if cmdPrefix == "" {
		transmitPowerFlagName = "transmitPower"
	} else {
		transmitPowerFlagName = fmt.Sprintf("%v.transmitPower", cmdPrefix)
	}

	var transmitPowerFlagDefault float64

	_ = cmd.PersistentFlags().Float64(transmitPowerFlagName, transmitPowerFlagDefault, transmitPowerDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Wds(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	wdsDescription := ``

	var wdsFlagName string
	if cmdPrefix == "" {
		wdsFlagName = "wds"
	} else {
		wdsFlagName = fmt.Sprintf("%v.wds", cmdPrefix)
	}

	var wdsFlagDefault bool

	_ = cmd.PersistentFlags().Bool(wdsFlagName, wdsFlagDefault, wdsDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WirelessMode(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	wirelessModeDescription := `Enum: ["ap","ap-ptp","ap-ptmp","ap-ptmp-airmax","ap-ptmp-airmax-mixed","ap-ptmp-airmax-ac","sta","sta-ptp","sta-ptmp","aprepeater","repeater","mesh"]. `

	var wirelessModeFlagName string
	if cmdPrefix == "" {
		wirelessModeFlagName = "wirelessMode"
	} else {
		wirelessModeFlagName = fmt.Sprintf("%v.wirelessMode", cmdPrefix)
	}

	var wirelessModeFlagDefault string

	_ = cmd.PersistentFlags().String(wirelessModeFlagName, wirelessModeFlagDefault, wirelessModeDescription)

	if err := cmd.RegisterFlagCompletionFunc(wirelessModeFlagName,
		func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
			var res []string
			if err := json.Unmarshal([]byte(`["ap","ap-ptp","ap-ptmp","ap-ptmp-airmax","ap-ptmp-airmax-mixed","ap-ptmp-airmax-ac","sta","sta-ptp","sta-ptmp","aprepeater","repeater","mesh"]`), &res); err != nil {
				panic(err)
			}
			return res, cobra.ShellCompDirectiveDefault
		}); err != nil {
		return err
	}

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WlanRxBytes(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	wlanRxBytesDescription := ``

	var wlanRxBytesFlagName string
	if cmdPrefix == "" {
		wlanRxBytesFlagName = "wlanRxBytes"
	} else {
		wlanRxBytesFlagName = fmt.Sprintf("%v.wlanRxBytes", cmdPrefix)
	}

	var wlanRxBytesFlagDefault float64

	_ = cmd.PersistentFlags().Float64(wlanRxBytesFlagName, wlanRxBytesFlagDefault, wlanRxBytesDescription)

	return nil
}

func registerDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WlanTxBytes(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	wlanTxBytesDescription := ``

	var wlanTxBytesFlagName string
	if cmdPrefix == "" {
		wlanTxBytesFlagName = "wlanTxBytes"
	} else {
		wlanTxBytesFlagName = fmt.Sprintf("%v.wlanTxBytes", cmdPrefix)
	}

	var wlanTxBytesFlagDefault float64

	_ = cmd.PersistentFlags().Float64(wlanTxBytesFlagName, wlanTxBytesFlagDefault, wlanTxBytesDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1Flags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, antennaAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1AntennaFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || antennaAdded

	err, apDeviceAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ApDeviceFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || apDeviceAdded

	err, apMacAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ApMacFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || apMacAdded

	err, authenticationAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1AuthenticationFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || authenticationAdded

	err, availableTxPowerRangeAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1AvailableTxPowerRangeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || availableTxPowerRangeAdded

	err, cableLengthAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CableLengthFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || cableLengthAdded

	err, cableSnrAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CableSnrFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || cableSnrAdded

	err, ccqAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CcqFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ccqAdded

	err, channelWidthAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ChannelWidthFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || channelWidthAdded

	err, countryCodeAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CountryCodeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || countryCodeAdded

	err, frequencyAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1FrequencyFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || frequencyAdded

	err, frequencyBandsAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1FrequencyBandsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || frequencyBandsAdded

	err, frequencyCenterAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1FrequencyCenterFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || frequencyCenterAdded

	err, gpsSignalAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1GpsSignalFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || gpsSignalAdded

	err, locationAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1LocationFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || locationAdded

	err, noiseFloorAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1NoiseFloorFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || noiseFloorAdded

	err, pollingAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1PollingFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || pollingAdded

	err, receiveChainsAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ReceiveChainsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || receiveChainsAdded

	err, remoteSignalAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RemoteSignalFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || remoteSignalAdded

	err, remoteSignal60gAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RemoteSignal60gFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || remoteSignal60gAdded

	err, rxCinrAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RxCinrFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || rxCinrAdded

	err, securityAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SecurityFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || securityAdded

	err, seriesAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SeriesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || seriesAdded

	err, signalChainAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SignalChainFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || signalChainAdded

	err, signalRemoteChainAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SignalRemoteChainFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || signalRemoteChainAdded

	err, ssidAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SsidFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ssidAdded

	err, stationNameAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1StationNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || stationNameAdded

	err, stationsCountAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1StationsCountFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || stationsCountAdded

	err, tddFramingAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TddFramingFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || tddFramingAdded

	err, transmitChainsAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TransmitChainsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || transmitChainsAdded

	err, transmitPowerAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TransmitPowerFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || transmitPowerAdded

	err, wdsAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WdsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || wdsAdded

	err, wirelessModeAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WirelessModeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || wirelessModeAdded

	err, wlanRxBytesAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WlanRxBytesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || wlanRxBytesAdded

	err, wlanTxBytesAdded := retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WlanTxBytesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || wlanTxBytesAdded

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1AntennaFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	antennaFlagName := fmt.Sprintf("%v.antenna", cmdPrefix)
	if cmd.Flags().Changed(antennaFlagName) {

		var antennaFlagName string
		if cmdPrefix == "" {
			antennaFlagName = "antenna"
		} else {
			antennaFlagName = fmt.Sprintf("%v.antenna", cmdPrefix)
		}

		antennaFlagValue, err := cmd.Flags().GetString(antennaFlagName)
		if err != nil {
			return err, false
		}
		m.Antenna = antennaFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ApDeviceFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	apDeviceFlagName := fmt.Sprintf("%v.apDevice", cmdPrefix)
	if cmd.Flags().Changed(apDeviceFlagName) {
		// info: complex object apDevice ApDevice is retrieved outside this Changed() block
	}
	apDeviceFlagValue := m.ApDevice
	if swag.IsZero(apDeviceFlagValue) {
		apDeviceFlagValue = &models.ApDevice{}
	}

	err, apDeviceAdded := retrieveModelApDeviceFlags(depth+1, apDeviceFlagValue, apDeviceFlagName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || apDeviceAdded
	if apDeviceAdded {
		m.ApDevice = apDeviceFlagValue
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ApMacFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	apMacFlagName := fmt.Sprintf("%v.apMac", cmdPrefix)
	if cmd.Flags().Changed(apMacFlagName) {

		var apMacFlagName string
		if cmdPrefix == "" {
			apMacFlagName = "apMac"
		} else {
			apMacFlagName = fmt.Sprintf("%v.apMac", cmdPrefix)
		}

		apMacFlagValue, err := cmd.Flags().GetString(apMacFlagName)
		if err != nil {
			return err, false
		}
		m.ApMac = apMacFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1AuthenticationFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	authenticationFlagName := fmt.Sprintf("%v.authentication", cmdPrefix)
	if cmd.Flags().Changed(authenticationFlagName) {

		var authenticationFlagName string
		if cmdPrefix == "" {
			authenticationFlagName = "authentication"
		} else {
			authenticationFlagName = fmt.Sprintf("%v.authentication", cmdPrefix)
		}

		authenticationFlagValue, err := cmd.Flags().GetString(authenticationFlagName)
		if err != nil {
			return err, false
		}
		m.Authentication = &authenticationFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1AvailableTxPowerRangeFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	availableTxPowerRangeFlagName := fmt.Sprintf("%v.availableTxPowerRange", cmdPrefix)
	if cmd.Flags().Changed(availableTxPowerRangeFlagName) {
		// info: complex object availableTxPowerRange AvailableTxPowerRange is retrieved outside this Changed() block
	}
	availableTxPowerRangeFlagValue := m.AvailableTxPowerRange
	if swag.IsZero(availableTxPowerRangeFlagValue) {
		availableTxPowerRangeFlagValue = &models.AvailableTxPowerRange{}
	}

	err, availableTxPowerRangeAdded := retrieveModelAvailableTxPowerRangeFlags(depth+1, availableTxPowerRangeFlagValue, availableTxPowerRangeFlagName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || availableTxPowerRangeAdded
	if availableTxPowerRangeAdded {
		m.AvailableTxPowerRange = availableTxPowerRangeFlagValue
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CableLengthFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	cableLengthFlagName := fmt.Sprintf("%v.cableLength", cmdPrefix)
	if cmd.Flags().Changed(cableLengthFlagName) {

		var cableLengthFlagName string
		if cmdPrefix == "" {
			cableLengthFlagName = "cableLength"
		} else {
			cableLengthFlagName = fmt.Sprintf("%v.cableLength", cmdPrefix)
		}

		cableLengthFlagValue, err := cmd.Flags().GetFloat64(cableLengthFlagName)
		if err != nil {
			return err, false
		}
		m.CableLength = cableLengthFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CableSnrFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	cableSnrFlagName := fmt.Sprintf("%v.cableSnr", cmdPrefix)
	if cmd.Flags().Changed(cableSnrFlagName) {

		var cableSnrFlagName string
		if cmdPrefix == "" {
			cableSnrFlagName = "cableSnr"
		} else {
			cableSnrFlagName = fmt.Sprintf("%v.cableSnr", cmdPrefix)
		}

		cableSnrFlagValue, err := cmd.Flags().GetFloat64(cableSnrFlagName)
		if err != nil {
			return err, false
		}
		m.CableSnr = cableSnrFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CcqFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	ccqFlagName := fmt.Sprintf("%v.ccq", cmdPrefix)
	if cmd.Flags().Changed(ccqFlagName) {

		var ccqFlagName string
		if cmdPrefix == "" {
			ccqFlagName = "ccq"
		} else {
			ccqFlagName = fmt.Sprintf("%v.ccq", cmdPrefix)
		}

		ccqFlagValue, err := cmd.Flags().GetFloat64(ccqFlagName)
		if err != nil {
			return err, false
		}
		m.Ccq = ccqFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ChannelWidthFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	channelWidthFlagName := fmt.Sprintf("%v.channelWidth", cmdPrefix)
	if cmd.Flags().Changed(channelWidthFlagName) {

		var channelWidthFlagName string
		if cmdPrefix == "" {
			channelWidthFlagName = "channelWidth"
		} else {
			channelWidthFlagName = fmt.Sprintf("%v.channelWidth", cmdPrefix)
		}

		channelWidthFlagValue, err := cmd.Flags().GetInt64(channelWidthFlagName)
		if err != nil {
			return err, false
		}
		m.ChannelWidth = &channelWidthFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1CountryCodeFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	countryCodeFlagName := fmt.Sprintf("%v.countryCode", cmdPrefix)
	if cmd.Flags().Changed(countryCodeFlagName) {

		var countryCodeFlagName string
		if cmdPrefix == "" {
			countryCodeFlagName = "countryCode"
		} else {
			countryCodeFlagName = fmt.Sprintf("%v.countryCode", cmdPrefix)
		}

		countryCodeFlagValue, err := cmd.Flags().GetInt64(countryCodeFlagName)
		if err != nil {
			return err, false
		}
		m.CountryCode = &countryCodeFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1FrequencyFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	frequencyFlagName := fmt.Sprintf("%v.frequency", cmdPrefix)
	if cmd.Flags().Changed(frequencyFlagName) {

		var frequencyFlagName string
		if cmdPrefix == "" {
			frequencyFlagName = "frequency"
		} else {
			frequencyFlagName = fmt.Sprintf("%v.frequency", cmdPrefix)
		}

		frequencyFlagValue, err := cmd.Flags().GetFloat64(frequencyFlagName)
		if err != nil {
			return err, false
		}
		m.Frequency = &frequencyFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1FrequencyBandsFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	frequencyBandsFlagName := fmt.Sprintf("%v.frequencyBands", cmdPrefix)
	if cmd.Flags().Changed(frequencyBandsFlagName) {
		// warning: frequencyBands array type FrequencyBands3 is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1FrequencyCenterFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	frequencyCenterFlagName := fmt.Sprintf("%v.frequencyCenter", cmdPrefix)
	if cmd.Flags().Changed(frequencyCenterFlagName) {

		var frequencyCenterFlagName string
		if cmdPrefix == "" {
			frequencyCenterFlagName = "frequencyCenter"
		} else {
			frequencyCenterFlagName = fmt.Sprintf("%v.frequencyCenter", cmdPrefix)
		}

		frequencyCenterFlagValue, err := cmd.Flags().GetString(frequencyCenterFlagName)
		if err != nil {
			return err, false
		}
		m.FrequencyCenter = frequencyCenterFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1GpsSignalFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	gpsSignalFlagName := fmt.Sprintf("%v.gpsSignal", cmdPrefix)
	if cmd.Flags().Changed(gpsSignalFlagName) {

		var gpsSignalFlagName string
		if cmdPrefix == "" {
			gpsSignalFlagName = "gpsSignal"
		} else {
			gpsSignalFlagName = fmt.Sprintf("%v.gpsSignal", cmdPrefix)
		}

		gpsSignalFlagValue, err := cmd.Flags().GetFloat64(gpsSignalFlagName)
		if err != nil {
			return err, false
		}
		m.GpsSignal = &gpsSignalFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1LocationFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	locationFlagName := fmt.Sprintf("%v.location", cmdPrefix)
	if cmd.Flags().Changed(locationFlagName) {
		// info: complex object location Location is retrieved outside this Changed() block
	}
	locationFlagValue := m.Location
	if swag.IsZero(locationFlagValue) {
		locationFlagValue = &models.Location{}
	}

	err, locationAdded := retrieveModelLocationFlags(depth+1, locationFlagValue, locationFlagName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || locationAdded
	if locationAdded {
		m.Location = locationFlagValue
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1NoiseFloorFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	noiseFloorFlagName := fmt.Sprintf("%v.noiseFloor", cmdPrefix)
	if cmd.Flags().Changed(noiseFloorFlagName) {

		var noiseFloorFlagName string
		if cmdPrefix == "" {
			noiseFloorFlagName = "noiseFloor"
		} else {
			noiseFloorFlagName = fmt.Sprintf("%v.noiseFloor", cmdPrefix)
		}

		noiseFloorFlagValue, err := cmd.Flags().GetString(noiseFloorFlagName)
		if err != nil {
			return err, false
		}
		m.NoiseFloor = noiseFloorFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1PollingFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	pollingFlagName := fmt.Sprintf("%v.polling", cmdPrefix)
	if cmd.Flags().Changed(pollingFlagName) {
		// info: complex object polling Polling is retrieved outside this Changed() block
	}
	pollingFlagValue := m.Polling
	if swag.IsZero(pollingFlagValue) {
		pollingFlagValue = &models.Polling{}
	}

	err, pollingAdded := retrieveModelPollingFlags(depth+1, pollingFlagValue, pollingFlagName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || pollingAdded
	if pollingAdded {
		m.Polling = pollingFlagValue
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1ReceiveChainsFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	receiveChainsFlagName := fmt.Sprintf("%v.receiveChains", cmdPrefix)
	if cmd.Flags().Changed(receiveChainsFlagName) {

		var receiveChainsFlagName string
		if cmdPrefix == "" {
			receiveChainsFlagName = "receiveChains"
		} else {
			receiveChainsFlagName = fmt.Sprintf("%v.receiveChains", cmdPrefix)
		}

		receiveChainsFlagValue, err := cmd.Flags().GetFloat64(receiveChainsFlagName)
		if err != nil {
			return err, false
		}
		m.ReceiveChains = receiveChainsFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RemoteSignalFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	remoteSignalFlagName := fmt.Sprintf("%v.remoteSignal", cmdPrefix)
	if cmd.Flags().Changed(remoteSignalFlagName) {

		var remoteSignalFlagName string
		if cmdPrefix == "" {
			remoteSignalFlagName = "remoteSignal"
		} else {
			remoteSignalFlagName = fmt.Sprintf("%v.remoteSignal", cmdPrefix)
		}

		remoteSignalFlagValue, err := cmd.Flags().GetFloat64(remoteSignalFlagName)
		if err != nil {
			return err, false
		}
		m.RemoteSignal = remoteSignalFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RemoteSignal60gFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	remoteSignal60gFlagName := fmt.Sprintf("%v.remoteSignal60g", cmdPrefix)
	if cmd.Flags().Changed(remoteSignal60gFlagName) {

		var remoteSignal60gFlagName string
		if cmdPrefix == "" {
			remoteSignal60gFlagName = "remoteSignal60g"
		} else {
			remoteSignal60gFlagName = fmt.Sprintf("%v.remoteSignal60g", cmdPrefix)
		}

		remoteSignal60gFlagValue, err := cmd.Flags().GetFloat64(remoteSignal60gFlagName)
		if err != nil {
			return err, false
		}
		m.RemoteSignal60g = remoteSignal60gFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1RxCinrFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	rxCinrFlagName := fmt.Sprintf("%v.rxCinr", cmdPrefix)
	if cmd.Flags().Changed(rxCinrFlagName) {

		var rxCinrFlagName string
		if cmdPrefix == "" {
			rxCinrFlagName = "rxCinr"
		} else {
			rxCinrFlagName = fmt.Sprintf("%v.rxCinr", cmdPrefix)
		}

		rxCinrFlagValue, err := cmd.Flags().GetFloat64(rxCinrFlagName)
		if err != nil {
			return err, false
		}
		m.RxCinr = rxCinrFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SecurityFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	securityFlagName := fmt.Sprintf("%v.security", cmdPrefix)
	if cmd.Flags().Changed(securityFlagName) {

		var securityFlagName string
		if cmdPrefix == "" {
			securityFlagName = "security"
		} else {
			securityFlagName = fmt.Sprintf("%v.security", cmdPrefix)
		}

		securityFlagValue, err := cmd.Flags().GetString(securityFlagName)
		if err != nil {
			return err, false
		}
		m.Security = &securityFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SeriesFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	seriesFlagName := fmt.Sprintf("%v.series", cmdPrefix)
	if cmd.Flags().Changed(seriesFlagName) {

		var seriesFlagName string
		if cmdPrefix == "" {
			seriesFlagName = "series"
		} else {
			seriesFlagName = fmt.Sprintf("%v.series", cmdPrefix)
		}

		seriesFlagValue, err := cmd.Flags().GetString(seriesFlagName)
		if err != nil {
			return err, false
		}
		m.Series = &seriesFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SignalChainFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	signalChainFlagName := fmt.Sprintf("%v.signalChain", cmdPrefix)
	if cmd.Flags().Changed(signalChainFlagName) {
		// warning: signalChain array type SignalChain is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SignalRemoteChainFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	signalRemoteChainFlagName := fmt.Sprintf("%v.signalRemoteChain", cmdPrefix)
	if cmd.Flags().Changed(signalRemoteChainFlagName) {
		// warning: signalRemoteChain array type SignalRemoteChain is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1SsidFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	ssidFlagName := fmt.Sprintf("%v.ssid", cmdPrefix)
	if cmd.Flags().Changed(ssidFlagName) {

		var ssidFlagName string
		if cmdPrefix == "" {
			ssidFlagName = "ssid"
		} else {
			ssidFlagName = fmt.Sprintf("%v.ssid", cmdPrefix)
		}

		ssidFlagValue, err := cmd.Flags().GetString(ssidFlagName)
		if err != nil {
			return err, false
		}
		m.Ssid = ssidFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1StationNameFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	stationNameFlagName := fmt.Sprintf("%v.stationName", cmdPrefix)
	if cmd.Flags().Changed(stationNameFlagName) {

		var stationNameFlagName string
		if cmdPrefix == "" {
			stationNameFlagName = "stationName"
		} else {
			stationNameFlagName = fmt.Sprintf("%v.stationName", cmdPrefix)
		}

		stationNameFlagValue, err := cmd.Flags().GetString(stationNameFlagName)
		if err != nil {
			return err, false
		}
		m.StationName = stationNameFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1StationsCountFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	stationsCountFlagName := fmt.Sprintf("%v.stationsCount", cmdPrefix)
	if cmd.Flags().Changed(stationsCountFlagName) {

		var stationsCountFlagName string
		if cmdPrefix == "" {
			stationsCountFlagName = "stationsCount"
		} else {
			stationsCountFlagName = fmt.Sprintf("%v.stationsCount", cmdPrefix)
		}

		stationsCountFlagValue, err := cmd.Flags().GetFloat64(stationsCountFlagName)
		if err != nil {
			return err, false
		}
		m.StationsCount = stationsCountFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TddFramingFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	tddFramingFlagName := fmt.Sprintf("%v.tddFraming", cmdPrefix)
	if cmd.Flags().Changed(tddFramingFlagName) {

		var tddFramingFlagName string
		if cmdPrefix == "" {
			tddFramingFlagName = "tddFraming"
		} else {
			tddFramingFlagName = fmt.Sprintf("%v.tddFraming", cmdPrefix)
		}

		tddFramingFlagValue, err := cmd.Flags().GetString(tddFramingFlagName)
		if err != nil {
			return err, false
		}
		m.TddFraming = tddFramingFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TransmitChainsFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	transmitChainsFlagName := fmt.Sprintf("%v.transmitChains", cmdPrefix)
	if cmd.Flags().Changed(transmitChainsFlagName) {

		var transmitChainsFlagName string
		if cmdPrefix == "" {
			transmitChainsFlagName = "transmitChains"
		} else {
			transmitChainsFlagName = fmt.Sprintf("%v.transmitChains", cmdPrefix)
		}

		transmitChainsFlagValue, err := cmd.Flags().GetFloat64(transmitChainsFlagName)
		if err != nil {
			return err, false
		}
		m.TransmitChains = transmitChainsFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1TransmitPowerFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	transmitPowerFlagName := fmt.Sprintf("%v.transmitPower", cmdPrefix)
	if cmd.Flags().Changed(transmitPowerFlagName) {

		var transmitPowerFlagName string
		if cmdPrefix == "" {
			transmitPowerFlagName = "transmitPower"
		} else {
			transmitPowerFlagName = fmt.Sprintf("%v.transmitPower", cmdPrefix)
		}

		transmitPowerFlagValue, err := cmd.Flags().GetFloat64(transmitPowerFlagName)
		if err != nil {
			return err, false
		}
		m.TransmitPower = transmitPowerFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WdsFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	wdsFlagName := fmt.Sprintf("%v.wds", cmdPrefix)
	if cmd.Flags().Changed(wdsFlagName) {

		var wdsFlagName string
		if cmdPrefix == "" {
			wdsFlagName = "wds"
		} else {
			wdsFlagName = fmt.Sprintf("%v.wds", cmdPrefix)
		}

		wdsFlagValue, err := cmd.Flags().GetBool(wdsFlagName)
		if err != nil {
			return err, false
		}
		m.Wds = wdsFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WirelessModeFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	wirelessModeFlagName := fmt.Sprintf("%v.wirelessMode", cmdPrefix)
	if cmd.Flags().Changed(wirelessModeFlagName) {

		var wirelessModeFlagName string
		if cmdPrefix == "" {
			wirelessModeFlagName = "wirelessMode"
		} else {
			wirelessModeFlagName = fmt.Sprintf("%v.wirelessMode", cmdPrefix)
		}

		wirelessModeFlagValue, err := cmd.Flags().GetString(wirelessModeFlagName)
		if err != nil {
			return err, false
		}
		m.WirelessMode = wirelessModeFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WlanRxBytesFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	wlanRxBytesFlagName := fmt.Sprintf("%v.wlanRxBytes", cmdPrefix)
	if cmd.Flags().Changed(wlanRxBytesFlagName) {

		var wlanRxBytesFlagName string
		if cmdPrefix == "" {
			wlanRxBytesFlagName = "wlanRxBytes"
		} else {
			wlanRxBytesFlagName = fmt.Sprintf("%v.wlanRxBytes", cmdPrefix)
		}

		wlanRxBytesFlagValue, err := cmd.Flags().GetFloat64(wlanRxBytesFlagName)
		if err != nil {
			return err, false
		}
		m.WlanRxBytes = wlanRxBytesFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1WlanTxBytesFlags(depth int, m *models.DEPRECATEDDeviceAirmaxPartiallyMovedPropertiesToInterfaceOrStation1, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	wlanTxBytesFlagName := fmt.Sprintf("%v.wlanTxBytes", cmdPrefix)
	if cmd.Flags().Changed(wlanTxBytesFlagName) {

		var wlanTxBytesFlagName string
		if cmdPrefix == "" {
			wlanTxBytesFlagName = "wlanTxBytes"
		} else {
			wlanTxBytesFlagName = fmt.Sprintf("%v.wlanTxBytes", cmdPrefix)
		}

		wlanTxBytesFlagValue, err := cmd.Flags().GetFloat64(wlanTxBytesFlagName)
		if err != nil {
			return err, false
		}
		m.WlanTxBytes = wlanTxBytesFlagValue

		retAdded = true
	}

	return nil, retAdded
}
