// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/byxorna/nycmesh-tool/client/sites"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationSitesPostSitesSiteidImagesImageidRotateleftCmd returns a cmd to handle operation postSitesSiteidImagesImageidRotateleft
func makeOperationSitesPostSitesSiteidImagesImageidRotateleftCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "postSitesSiteidImagesImageidRotateleft",
		Short: ``,
		RunE:  runOperationSitesPostSitesSiteidImagesImageidRotateleft,
	}

	if err := registerOperationSitesPostSitesSiteidImagesImageidRotateleftParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationSitesPostSitesSiteidImagesImageidRotateleft uses cmd flags to call endpoint api
func runOperationSitesPostSitesSiteidImagesImageidRotateleft(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := sites.NewPostSitesSiteidImagesImageidRotateleftParams()
	if err, _ := retrieveOperationSitesPostSitesSiteidImagesImageidRotateleftImageIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationSitesPostSitesSiteidImagesImageidRotateleftSiteIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationSitesPostSitesSiteidImagesImageidRotateleftResult(appCli.Sites.PostSitesSiteidImagesImageidRotateleft(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationSitesPostSitesSiteidImagesImageidRotateleftParamFlags registers all flags needed to fill params
func registerOperationSitesPostSitesSiteidImagesImageidRotateleftParamFlags(cmd *cobra.Command) error {
	if err := registerOperationSitesPostSitesSiteidImagesImageidRotateleftImageIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSitesPostSitesSiteidImagesImageidRotateleftSiteIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationSitesPostSitesSiteidImagesImageidRotateleftImageIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	imageIdDescription := `Required. `

	var imageIdFlagName string
	if cmdPrefix == "" {
		imageIdFlagName = "imageId"
	} else {
		imageIdFlagName = fmt.Sprintf("%v.imageId", cmdPrefix)
	}

	var imageIdFlagDefault string

	_ = cmd.PersistentFlags().String(imageIdFlagName, imageIdFlagDefault, imageIdDescription)

	return nil
}
func registerOperationSitesPostSitesSiteidImagesImageidRotateleftSiteIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	siteIdDescription := `Required. `

	var siteIdFlagName string
	if cmdPrefix == "" {
		siteIdFlagName = "siteId"
	} else {
		siteIdFlagName = fmt.Sprintf("%v.siteId", cmdPrefix)
	}

	var siteIdFlagDefault string

	_ = cmd.PersistentFlags().String(siteIdFlagName, siteIdFlagDefault, siteIdDescription)

	return nil
}

func retrieveOperationSitesPostSitesSiteidImagesImageidRotateleftImageIDFlag(m *sites.PostSitesSiteidImagesImageidRotateleftParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("imageId") {

		var imageIdFlagName string
		if cmdPrefix == "" {
			imageIdFlagName = "imageId"
		} else {
			imageIdFlagName = fmt.Sprintf("%v.imageId", cmdPrefix)
		}

		imageIdFlagValue, err := cmd.Flags().GetString(imageIdFlagName)
		if err != nil {
			return err, false
		}
		m.ImageID = imageIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationSitesPostSitesSiteidImagesImageidRotateleftSiteIDFlag(m *sites.PostSitesSiteidImagesImageidRotateleftParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("siteId") {

		var siteIdFlagName string
		if cmdPrefix == "" {
			siteIdFlagName = "siteId"
		} else {
			siteIdFlagName = fmt.Sprintf("%v.siteId", cmdPrefix)
		}

		siteIdFlagValue, err := cmd.Flags().GetString(siteIdFlagName)
		if err != nil {
			return err, false
		}
		m.SiteID = siteIdFlagValue

	}
	return nil, retAdded
}

// parseOperationSitesPostSitesSiteidImagesImageidRotateleftResult parses request result and return the string content
func parseOperationSitesPostSitesSiteidImagesImageidRotateleftResult(resp0 *sites.PostSitesSiteidImagesImageidRotateleftOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*sites.PostSitesSiteidImagesImageidRotateleftOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*sites.PostSitesSiteidImagesImageidRotateleftBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*sites.PostSitesSiteidImagesImageidRotateleftUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*sites.PostSitesSiteidImagesImageidRotateleftForbidden)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*sites.PostSitesSiteidImagesImageidRotateleftInternalServerError)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
