// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/byxorna/nycmesh-tool/client/devices"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockCmd returns a cmd to handle operation postDevicesUisprsIdDhcpServersServernameUnblock
func makeOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "postDevicesUisprsIdDhcpServersServernameUnblock",
		Short: ``,
		RunE:  runOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblock,
	}

	if err := registerOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblock uses cmd flags to call endpoint api
func runOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblock(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := devices.NewPostDevicesUisprsIDDhcpServersServernameUnblockParams()
	if err, _ := retrieveOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockServerNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockResult(appCli.Devices.PostDevicesUisprsIDDhcpServersServernameUnblock(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockParamFlags registers all flags needed to fill params
func registerOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockParamFlags(cmd *cobra.Command) error {
	if err := registerOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockServerNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. `

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}
func registerOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockServerNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	serverNameDescription := `Required. `

	var serverNameFlagName string
	if cmdPrefix == "" {
		serverNameFlagName = "serverName"
	} else {
		serverNameFlagName = fmt.Sprintf("%v.serverName", cmdPrefix)
	}

	var serverNameFlagDefault string

	_ = cmd.PersistentFlags().String(serverNameFlagName, serverNameFlagDefault, serverNameDescription)

	return nil
}

func retrieveOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockIDFlag(m *devices.PostDevicesUisprsIDDhcpServersServernameUnblockParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}
func retrieveOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockServerNameFlag(m *devices.PostDevicesUisprsIDDhcpServersServernameUnblockParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("serverName") {

		var serverNameFlagName string
		if cmdPrefix == "" {
			serverNameFlagName = "serverName"
		} else {
			serverNameFlagName = fmt.Sprintf("%v.serverName", cmdPrefix)
		}

		serverNameFlagValue, err := cmd.Flags().GetString(serverNameFlagName)
		if err != nil {
			return err, false
		}
		m.ServerName = serverNameFlagValue

	}
	return nil, retAdded
}

// parseOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockResult parses request result and return the string content
func parseOperationDevicesPostDevicesUisprsIDDhcpServersServernameUnblockResult(resp0 *devices.PostDevicesUisprsIDDhcpServersServernameUnblockOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*devices.PostDevicesUisprsIDDhcpServersServernameUnblockOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*devices.PostDevicesUisprsIDDhcpServersServernameUnblockBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*devices.PostDevicesUisprsIDDhcpServersServernameUnblockUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*devices.PostDevicesUisprsIDDhcpServersServernameUnblockForbidden)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*devices.PostDevicesUisprsIDDhcpServersServernameUnblockNotFound)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*devices.PostDevicesUisprsIDDhcpServersServernameUnblockInternalServerError)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
