// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/byxorna/nycmesh-tool/models"
)

// DeleteUsersIDReader is a Reader for the DeleteUsersID structure.
type DeleteUsersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUsersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteUsersIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteUsersIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteUsersIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteUsersIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteUsersIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteUsersIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteUsersIDOK creates a DeleteUsersIDOK with default headers values
func NewDeleteUsersIDOK() *DeleteUsersIDOK {
	return &DeleteUsersIDOK{}
}

/* DeleteUsersIDOK describes a response with status code 200, with default header values.

Successful
*/
type DeleteUsersIDOK struct {
	Payload *models.Status
}

func (o *DeleteUsersIDOK) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdOK  %+v", 200, o.Payload)
}
func (o *DeleteUsersIDOK) GetPayload() *models.Status {
	return o.Payload
}

func (o *DeleteUsersIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUsersIDBadRequest creates a DeleteUsersIDBadRequest with default headers values
func NewDeleteUsersIDBadRequest() *DeleteUsersIDBadRequest {
	return &DeleteUsersIDBadRequest{}
}

/* DeleteUsersIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteUsersIDBadRequest struct {
	Payload *models.Error
}

func (o *DeleteUsersIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteUsersIDBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteUsersIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUsersIDUnauthorized creates a DeleteUsersIDUnauthorized with default headers values
func NewDeleteUsersIDUnauthorized() *DeleteUsersIDUnauthorized {
	return &DeleteUsersIDUnauthorized{}
}

/* DeleteUsersIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteUsersIDUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteUsersIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteUsersIDUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteUsersIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUsersIDForbidden creates a DeleteUsersIDForbidden with default headers values
func NewDeleteUsersIDForbidden() *DeleteUsersIDForbidden {
	return &DeleteUsersIDForbidden{}
}

/* DeleteUsersIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteUsersIDForbidden struct {
	Payload *models.Error
}

func (o *DeleteUsersIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdForbidden  %+v", 403, o.Payload)
}
func (o *DeleteUsersIDForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteUsersIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUsersIDNotFound creates a DeleteUsersIDNotFound with default headers values
func NewDeleteUsersIDNotFound() *DeleteUsersIDNotFound {
	return &DeleteUsersIDNotFound{}
}

/* DeleteUsersIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteUsersIDNotFound struct {
	Payload *models.Error
}

func (o *DeleteUsersIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdNotFound  %+v", 404, o.Payload)
}
func (o *DeleteUsersIDNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteUsersIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUsersIDInternalServerError creates a DeleteUsersIDInternalServerError with default headers values
func NewDeleteUsersIDInternalServerError() *DeleteUsersIDInternalServerError {
	return &DeleteUsersIDInternalServerError{}
}

/* DeleteUsersIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteUsersIDInternalServerError struct {
	Payload *models.Error
}

func (o *DeleteUsersIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteUsersIDInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteUsersIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
