// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation d e p r e c a t e d device air fiber partially moved properties to interface or station
//
// swagger:model [DEPRECATED]DeviceAirFiber - partially moved properties to interface or station.
type DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation struct {

	// antenna
	Antenna string `json:"antenna,omitempty"`

	// ap device
	ApDevice *ApDevice1 `json:"apDevice,omitempty"`

	// ap mac
	ApMac string `json:"apMac,omitempty"`

	// authentication
	// Enum: [psk psk2 ent none]
	Authentication string `json:"authentication,omitempty"`

	// bridge mode
	// Enum: [hw sw]
	BridgeMode string `json:"bridgeMode,omitempty"`

	// channel width
	// Minimum: 0
	ChannelWidth *int64 `json:"channelWidth,omitempty"`

	// country code
	// Minimum: 0
	CountryCode *int64 `json:"countryCode,omitempty"`

	// frame length
	FrameLength float64 `json:"frameLength,omitempty"`

	// frequency
	// Example: 5400
	// Minimum: 0
	Frequency *float64 `json:"frequency,omitempty"`

	// frequency bands
	FrequencyBands FrequencyBands1 `json:"frequencyBands,omitempty"`

	// frequency center
	FrequencyCenter string `json:"frequencyCenter,omitempty"`

	// noise floor
	NoiseFloor string `json:"noiseFloor,omitempty"`

	// receive chains
	ReceiveChains float64 `json:"receiveChains,omitempty"`

	// remote signal
	RemoteSignal string `json:"remoteSignal,omitempty"`

	// security
	// Enum: [wep wpa wpa-psk wpa2 enabled none]
	Security string `json:"security,omitempty"`

	// series
	// Enum: [LTU classic G60]
	Series string `json:"series,omitempty"`

	// signal chain
	SignalChain SignalChain `json:"signalChain,omitempty"`

	// signal remote chain
	SignalRemoteChain SignalRemoteChain `json:"signalRemoteChain,omitempty"`

	// SSID
	// Required: true
	Ssid *string `json:"ssid"`

	// station name
	StationName string `json:"stationName,omitempty"`

	// stations count
	StationsCount float64 `json:"stationsCount,omitempty"`

	// transmit chains
	TransmitChains float64 `json:"transmitChains,omitempty"`

	// transmit duty cycle
	TransmitDutyCycle float64 `json:"transmitDutyCycle,omitempty"`

	// transmit eirp
	TransmitEirp float64 `json:"transmitEirp,omitempty"`

	// transmit power
	TransmitPower float64 `json:"transmitPower,omitempty"`

	// wireless mode
	// Enum: [ap ap-ptp ap-ptmp ap-ptmp-airmax ap-ptmp-airmax-mixed ap-ptmp-airmax-ac sta sta-ptp sta-ptmp aprepeater repeater mesh]
	WirelessMode string `json:"wirelessMode,omitempty"`
}

// Validate validates this d e p r e c a t e d device air fiber partially moved properties to interface or station
func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApDevice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAuthentication(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBridgeMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChannelWidth(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCountryCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFrequency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFrequencyBands(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecurity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignalChain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignalRemoteChain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSsid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWirelessMode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateApDevice(formats strfmt.Registry) error {
	if swag.IsZero(m.ApDevice) { // not required
		return nil
	}

	if m.ApDevice != nil {
		if err := m.ApDevice.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apDevice")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apDevice")
			}
			return err
		}
	}

	return nil
}

var dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeAuthenticationPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["psk","psk2","ent","none"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeAuthenticationPropEnum = append(dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeAuthenticationPropEnum, v)
	}
}

const (

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationAuthenticationPsk captures enum value "psk"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationAuthenticationPsk string = "psk"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationAuthenticationPsk2 captures enum value "psk2"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationAuthenticationPsk2 string = "psk2"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationAuthenticationEnt captures enum value "ent"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationAuthenticationEnt string = "ent"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationAuthenticationNone captures enum value "none"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationAuthenticationNone string = "none"
)

// prop value enum
func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateAuthenticationEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeAuthenticationPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateAuthentication(formats strfmt.Registry) error {
	if swag.IsZero(m.Authentication) { // not required
		return nil
	}

	// value enum
	if err := m.validateAuthenticationEnum("authentication", "body", m.Authentication); err != nil {
		return err
	}

	return nil
}

var dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeBridgeModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["hw","sw"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeBridgeModePropEnum = append(dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeBridgeModePropEnum, v)
	}
}

const (

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationBridgeModeHw captures enum value "hw"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationBridgeModeHw string = "hw"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationBridgeModeSw captures enum value "sw"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationBridgeModeSw string = "sw"
)

// prop value enum
func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateBridgeModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeBridgeModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateBridgeMode(formats strfmt.Registry) error {
	if swag.IsZero(m.BridgeMode) { // not required
		return nil
	}

	// value enum
	if err := m.validateBridgeModeEnum("bridgeMode", "body", m.BridgeMode); err != nil {
		return err
	}

	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateChannelWidth(formats strfmt.Registry) error {
	if swag.IsZero(m.ChannelWidth) { // not required
		return nil
	}

	if err := validate.MinimumInt("channelWidth", "body", *m.ChannelWidth, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateCountryCode(formats strfmt.Registry) error {
	if swag.IsZero(m.CountryCode) { // not required
		return nil
	}

	if err := validate.MinimumInt("countryCode", "body", *m.CountryCode, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateFrequency(formats strfmt.Registry) error {
	if swag.IsZero(m.Frequency) { // not required
		return nil
	}

	if err := validate.Minimum("frequency", "body", *m.Frequency, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateFrequencyBands(formats strfmt.Registry) error {
	if swag.IsZero(m.FrequencyBands) { // not required
		return nil
	}

	if err := m.FrequencyBands.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("frequencyBands")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("frequencyBands")
		}
		return err
	}

	return nil
}

var dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeSecurityPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["wep","wpa","wpa-psk","wpa2","enabled","none"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeSecurityPropEnum = append(dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeSecurityPropEnum, v)
	}
}

const (

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityWep captures enum value "wep"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityWep string = "wep"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityWpa captures enum value "wpa"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityWpa string = "wpa"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityWpaDashPsk captures enum value "wpa-psk"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityWpaDashPsk string = "wpa-psk"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityWpa2 captures enum value "wpa2"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityWpa2 string = "wpa2"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityEnabled captures enum value "enabled"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityEnabled string = "enabled"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityNone captures enum value "none"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSecurityNone string = "none"
)

// prop value enum
func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateSecurityEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeSecurityPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateSecurity(formats strfmt.Registry) error {
	if swag.IsZero(m.Security) { // not required
		return nil
	}

	// value enum
	if err := m.validateSecurityEnum("security", "body", m.Security); err != nil {
		return err
	}

	return nil
}

var dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeSeriesPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["LTU","classic","G60"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeSeriesPropEnum = append(dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeSeriesPropEnum, v)
	}
}

const (

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSeriesLTU captures enum value "LTU"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSeriesLTU string = "LTU"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSeriesClassic captures enum value "classic"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSeriesClassic string = "classic"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSeriesG60 captures enum value "G60"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationSeriesG60 string = "G60"
)

// prop value enum
func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateSeriesEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeSeriesPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateSeries(formats strfmt.Registry) error {
	if swag.IsZero(m.Series) { // not required
		return nil
	}

	// value enum
	if err := m.validateSeriesEnum("series", "body", m.Series); err != nil {
		return err
	}

	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateSignalChain(formats strfmt.Registry) error {
	if swag.IsZero(m.SignalChain) { // not required
		return nil
	}

	if err := m.SignalChain.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("signalChain")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("signalChain")
		}
		return err
	}

	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateSignalRemoteChain(formats strfmt.Registry) error {
	if swag.IsZero(m.SignalRemoteChain) { // not required
		return nil
	}

	if err := m.SignalRemoteChain.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("signalRemoteChain")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("signalRemoteChain")
		}
		return err
	}

	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateSsid(formats strfmt.Registry) error {

	if err := validate.Required("ssid", "body", m.Ssid); err != nil {
		return err
	}

	return nil
}

var dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeWirelessModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ap","ap-ptp","ap-ptmp","ap-ptmp-airmax","ap-ptmp-airmax-mixed","ap-ptmp-airmax-ac","sta","sta-ptp","sta-ptmp","aprepeater","repeater","mesh"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeWirelessModePropEnum = append(dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeWirelessModePropEnum, v)
	}
}

const (

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeAp captures enum value "ap"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeAp string = "ap"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeApDashPtp captures enum value "ap-ptp"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeApDashPtp string = "ap-ptp"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeApDashPtmp captures enum value "ap-ptmp"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeApDashPtmp string = "ap-ptmp"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeApDashPtmpDashAirmax captures enum value "ap-ptmp-airmax"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeApDashPtmpDashAirmax string = "ap-ptmp-airmax"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeApDashPtmpDashAirmaxDashMixed captures enum value "ap-ptmp-airmax-mixed"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeApDashPtmpDashAirmaxDashMixed string = "ap-ptmp-airmax-mixed"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeApDashPtmpDashAirmaxDashAc captures enum value "ap-ptmp-airmax-ac"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeApDashPtmpDashAirmaxDashAc string = "ap-ptmp-airmax-ac"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeSta captures enum value "sta"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeSta string = "sta"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeStaDashPtp captures enum value "sta-ptp"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeStaDashPtp string = "sta-ptp"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeStaDashPtmp captures enum value "sta-ptmp"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeStaDashPtmp string = "sta-ptmp"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeAprepeater captures enum value "aprepeater"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeAprepeater string = "aprepeater"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeRepeater captures enum value "repeater"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeRepeater string = "repeater"

	// DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeMesh captures enum value "mesh"
	DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationWirelessModeMesh string = "mesh"
)

// prop value enum
func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateWirelessModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, dEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStationTypeWirelessModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) validateWirelessMode(formats strfmt.Registry) error {
	if swag.IsZero(m.WirelessMode) { // not required
		return nil
	}

	// value enum
	if err := m.validateWirelessModeEnum("wirelessMode", "body", m.WirelessMode); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this d e p r e c a t e d device air fiber partially moved properties to interface or station based on the context it is used
func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateApDevice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFrequencyBands(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSignalChain(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSignalRemoteChain(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) contextValidateApDevice(ctx context.Context, formats strfmt.Registry) error {

	if m.ApDevice != nil {
		if err := m.ApDevice.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apDevice")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apDevice")
			}
			return err
		}
	}

	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) contextValidateFrequencyBands(ctx context.Context, formats strfmt.Registry) error {

	if err := m.FrequencyBands.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("frequencyBands")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("frequencyBands")
		}
		return err
	}

	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) contextValidateSignalChain(ctx context.Context, formats strfmt.Registry) error {

	if err := m.SignalChain.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("signalChain")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("signalChain")
		}
		return err
	}

	return nil
}

func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) contextValidateSignalRemoteChain(ctx context.Context, formats strfmt.Registry) error {

	if err := m.SignalRemoteChain.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("signalRemoteChain")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("signalRemoteChain")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation) UnmarshalBinary(b []byte) error {
	var res DEPRECATEDDeviceAirFiberPartiallyMovedPropertiesToInterfaceOrStation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
