// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Model19 model 19
//
// swagger:model Model 19
type Model19 struct {

	// alerts
	Alerts Alerts `json:"alerts,omitempty"`

	// x
	X float64 `json:"x,omitempty"`

	// y
	Y float64 `json:"y,omitempty"`
}

// Validate validates this model 19
func (m *Model19) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlerts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Model19) validateAlerts(formats strfmt.Registry) error {
	if swag.IsZero(m.Alerts) { // not required
		return nil
	}

	if err := m.Alerts.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("alerts")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("alerts")
		}
		return err
	}

	return nil
}

// ContextValidate validate this model 19 based on the context it is used
func (m *Model19) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAlerts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Model19) contextValidateAlerts(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Alerts.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("alerts")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("alerts")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Model19) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Model19) UnmarshalBinary(b []byte) error {
	var res Model19
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
