// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// RegulatoryDomainBands regulatory domain bands
//
// swagger:model regulatoryDomainBands
type RegulatoryDomainBands []string

// Validate validates this regulatory domain bands
func (m RegulatoryDomainBands) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this regulatory domain bands based on context it is used
func (m RegulatoryDomainBands) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
